Repository ChecKHUMate/Demo_ChecKHUMate, pull requests merged in 2024-05, with the labels that each got.

#2 feat : 마이페이지 html, css 추가
  frontend/static/css/my_page.css
  frontend/static/css/my_page_style.css
  frontend/static/image/mypage/KakaoTalk_20240514_121316096.jpg
  frontend/static/image/mypage/containeri2712-ulys-200h.png
  frontend/static/image/mypage/containeri2716-4pm-200h.png
  frontend/static/image/mypage/containeri2716-766-200h.png
  frontend/static/image/mypage/containeri2716-7ek-200h.png
  frontend/static/image/mypage/containeri2716-7kbh-200h.png
  frontend/static/image/mypage/containeri2716-7o1r-200h.png
  frontend/static/image/mypage/containeri2716-ipxg-200h.png
  frontend/static/image/mypage/containeri2716-rr8-200h.png
  frontend/static/image/mypage/containeri2716-u71t-200h.png
  frontend/static/image/mypage/ellipse1i2723-j3dc-200h.png
  frontend/static/image/mypage/imagei2716-v2e6-200h.png
  frontend/static/image/mypage/logo1i2716-2sn-200h.png
  frontend/static/image/mypage/rectangle23i2716-pq7u-200h.png
  frontend/static/image/mypage/rectangle23i2716-qnz-200h.png
  frontend/static/image/mypage/rectangle2716-qet9-1100w.png
  frontend/templates/my_page.html
  frontend/templates/mypage.html
Labels: enhancement

#5 [feat] 룸메이트 프로필 창
  .idea/.gitignore
  .idea/Demo_ChecKHUMate.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  frontend/static/css/check.css
  frontend/static/image/checkpage/check.png
  frontend/static/image/checkpage/cover1.png
  frontend/static/image/checkpage/profile1.png
  frontend/static/image/checkpage/profile2.png
  frontend/static/image/checkpage/profile3.png
  frontend/static/js/addEventListener.js
  frontend/static/js/modal.js
  frontend/templates/check.html
Labels: feature

#6 fix: 룸메이트 프로필 오류 해결
  .idea/misc.xml
  frontend/static/css/check.css
  frontend/static/image/checkpage/cover2.png
  frontend/static/image/checkpage/cover3.png
  frontend/static/image/checkpage/profile2.png
  frontend/templates/check.html
Labels: wontfix, fix
